services:
  accommodations-db:
    image: postgres:15
    env_file:
      - .env
    networks:
      - devops

  accommodations-service:
    build: .
    env_file:
      - .env
    command: sh -c "sleep 10 && python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    ports:
      - "8001:8000"
    depends_on:
      - accommodations-db
    networks:
      - devops

networks:
  devops:
    name: devops-network
    driver: bridge
